version: '3.1'
networks:
  default:
    external:
      name: embers-net
services:
  cityofbrass:
    build: .
    command: foreman start
    ports:
      - '5000:5000'
    volumes:
      - ./:/usr/src/app
    links:
      - redis
      - postgres
  redis:
    image: redis:latest
  postgres:
    image: postgres
