# Add application configuration variables here, as shown below.
AWS_ACCESS_KEY_ID: 
AWS_SECRET_ACCESS_KEY: 
AWS_REGION: us-east-1

DEFAULT_BASE_URL: localhost:5000
DEFAULT_FROM_EMAIL: support@test.com

SES_USER: 
SES_PASS: 

PAPERCLIP_SECRET: 
FOG_DIRECTORY: 

DEVISE_SECRET: 
DEVISE_PEPPER: 

WEB_CONCURRENCY: "0"
MAX_THREADS: "16"

STRIPE_SECRET_KEY: 
STRIPE_PUBLISHABLE_KEY: 
STRIPE_WEBHOOK_TOKEN: 

REDISCLOUD_URL: redis://redis:6379
REDIS_PROVIDER: REDISCLOUD_URL
ACTIVEPLAY_SECRET: 
ACTIVEPLAY_URL: http://localhost:5050
